---
AWSTemplateFormatVersion: '2010-09-09'
Description: Client VPN Route Setup Portfolio for Service Catalog
Parameters:
  PortfolioProvider:
    Type: String
    Description: Provider Name
    Default: Vertical Relevance
  PortfolioName:
    Type: String
    Description: Portfolio Name
    Default: Service Catalog Client VPN Auth and Route Setup for New/Existing VPCs
  PortfolioDescription:
    Type: String
    Description: Portfolio Description
    Default: Service Catalog Portfolio that contains products for setting up a new Client VPN Route configurations for
      VPCs that are requesting access to a centralized network hub Client VPN. This portfolio should
      live inside a centrallized network hub account.
  RepoRootURL:
    Type: String
    Description: Root url for the repo containing the product templates.
    Default: ''
  LinkedIamUser:
    Type: String
    Description: "(Optional) Your IAM User to allow access for you to launch products from this portfolio"
    Default: ''
  LinkedIamRoleArn:
    Type: String
    Description: "(Optional) Your IAM Role ARN to allow access for you to launch products from this portfolio"
    Default: ''
Conditions:
  CondLinkYourIamUser:
    Fn::Not:
      - Fn::Equals:
          - Ref: LinkedIamUser
          - ''
  CondLinkYourIamRole:
    Fn::Not:
      - Fn::Equals:
          - Ref: LinkedIamRoleArn
          - ''
Resources:
  ClientVpnAuthRouteSetupportfolio:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      ProviderName:
        Ref: PortfolioProvider
      Description:
        Ref: PortfolioDescription
      DisplayName:
        Ref: PortfolioName
  LinkYourIamUser:
    Condition: CondLinkYourIamUser
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Properties:
      PrincipalARN: !Sub 'arn:aws:iam::${AWS::AccountId}:user/${LinkedIamUser}'
      PortfolioId:
        Ref: ClientVpnAuthRouteSetupportfolio
      PrincipalType: IAM
  LinkYourIamRole:
    Condition: CondLinkYourIamRole
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Properties:
      PrincipalARN: !Ref LinkedIamRoleArn
      PortfolioId:
        Ref: ClientVpnAuthRouteSetupportfolio
      PrincipalType: IAM
  ClientVpnAuthRouteSetupProduct:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        PortfolioProvider:
          Ref: PortfolioProvider
        PortfolioId:
          Ref: ClientVpnAuthRouteSetupportfolio
        RepoRootURL:
          Ref: RepoRootURL
      TemplateURL:
        Fn::Sub: "${RepoRootURL}vpn/sc-product-vpn-route-setup.yml"
      TimeoutInMinutes: 5
Outputs:
  ClientVpnAuthRouteSetupProductId:
    Value:
      Fn::GetAtt:
      - ClientVpnAuthRouteSetupProduct
      - Outputs.ProductId
